### ISSUE TITLE
이코드가 이상해요...ㅠ

### ISSUE THREAD

**Issue by Shin-Yeonghwa** [Shin-Yeonghwa/JaviS#12]
https://github.com/Shin-Yeonghwa/JaviS/blob/c13c34390ae21b30daac44a53c0e7218b1c4767d/src/ShinYeongHwa/ShinYeongHwa_0402.html#L20

button의 valie 값중 1은 불린값인지?? 바위 : 보 결과 값이 이상하네요.

**Comment by Shin-Yeonghwa** [comment]
var userResult = Number(document.getElementById(value.id).value);
이렇게 수정을 하는건 어떨까요???

**Comment by qkrwlgnstm** [comment]
button의 value값은 string으로 parseInt를 사용하여 number로 변환 ㄱㄱ
