### ISSUE TITLE
왜? const로 하셨는지 궁금해요 ㅎㅎ

### ISSUE THREAD

**Issue by Shin-Yeonghwa** [Shin-Yeonghwa/JaviS#14]
@qkrwlgnstm 님~
https://github.com/Shin-Yeonghwa/JaviS/blob/c13c34390ae21b30daac44a53c0e7218b1c4767d/src/ParkJiHoon/ParkJiHoon_0401.html#L25-L27

**Comment by qkrwlgnstm** [comment]
해당 부분의 값을 재할당 안하기 때문에 const로 적용

**Comment by Shin-Yeonghwa** [comment]
var를 쓰고 재할당 하는 코드도 보여주세요

**Comment by qkrwlgnstm** [comment]
const를 var로 변경하고 재할당 안하면 되는거 아님요?ㅋㅋ
