### ISSUE TITLE
증감연산자

### ISSUE THREAD

**Issue by KimKyeongEun** [Shin-Yeonghwa/JaviS#3]
아래 페이지 이해되면 헷갈리지 않을거 같습다.ㅋ
[증감연산자](http://tcpschool.com/javascript/js_operator_incAndDec)

**Comment by NoGeonHee** [comment]
추가적으로,
- ++ i
 - 전치증가 연산자 : 먼저 피연사자를 증가시킨 다음 이 증가된 값을 결과로 내 놓는다.
 - 예시 : i = 1, j = ++ i
 - 결과 : i = 2, j = 2
- i ++
 - 후치증가 연산자 : 피연산자를 증사 시키지만 결과로는 원래의 증가되지 않은 값을 내 놓는다.
 - 예시 : i = 1, j = i ++
 - 결과 : i = 2, j = 1
